"""Stage 1: one-dimensional procedural validation."""

from .train import (
    SYNTHETIC_1D_SPEC,
    SYNTHETIC_CHECKPOINT_KIND,
    SYNTHETIC_LOSS_KEYS,
    SYNTHETIC_METRIC_KEYS,
    SYNTHETIC_MODEL_NAME,
    MeanSyntheticBaseline,
    RandomSyntheticBaseline,
    SyntheticBaselinePredictions,
    SyntheticTrainingConfig,
    build_synthetic_model,
    compute_synthetic_evaluation_metrics,
    compute_synthetic_training_losses,
    evaluate_synthetic_baselines,
    evaluate_synthetic_model,
    generate_hierarchical_data,
    make_empty_history,
    make_train_permutation,
    restore_synthetic_checkpoint,
    save_synthetic_checkpoint,
    seed_everything,
    synthetic_spec_metadata,
    train_and_evaluate,
    train_synthetic_epoch,
)

__all__ = [
    "SYNTHETIC_1D_SPEC",
    "SYNTHETIC_LOSS_KEYS",
    "SYNTHETIC_METRIC_KEYS",
    "synthetic_spec_metadata",
    "save_synthetic_checkpoint",
    "restore_synthetic_checkpoint",
    "SYNTHETIC_MODEL_NAME",
    "SYNTHETIC_CHECKPOINT_KIND",
    "MeanSyntheticBaseline",
    "RandomSyntheticBaseline",
    "SyntheticBaselinePredictions",
    "SyntheticTrainingConfig",
    "build_synthetic_model",
    "compute_synthetic_evaluation_metrics",
    "compute_synthetic_training_losses",
    "evaluate_synthetic_baselines",
    "train_synthetic_epoch",
    "evaluate_synthetic_model",
    "generate_hierarchical_data",
    "make_empty_history",
    "make_train_permutation",
    "seed_everything",
    "train_and_evaluate",
]
