"""Stage 2: scriptable low-resolution Super Mario Bros environment."""

from .adapter import (
    BLOCK_SMB_SPEC,
    SCENARIOS_DIR,
    BlockSMBObservationConfig,
    BlockSMBStage,
)
from .env import BlockSMBRewardConfig, MarioScenarioEnv
from .train import (
    BLOCK_SMB_CHECKPOINT_KIND,
    BLOCK_SMB_MODEL_NAME,
    BlockSMBReplayBuffer,
    BlockSMBTrainingConfig,
    BlockSMBTrajectory,
    BlockSMBTransition,
    SequentialBlockSMBVectorEnv,
    build_curriculum,
    evaluate_block_smb,
    restore_block_smb_checkpoint,
    save_block_smb_checkpoint,
    train_and_evaluate_block_smb,
    train_block_smb_epoch,
)
from .success import (
    FIXED_BLOCK_SMB_SUCCESS_THRESHOLDS,
    BlockSMBSuccessThreshold,
    evaluate_fixed_success_thresholds,
    evaluate_success_threshold,
    fixed_scenario_success_threshold,
    summarize_fixed_success_metrics,
)
from .scripted_policy import (
    SCRIPTED_BLOCK_SMB_CHECKPOINT_KIND,
    SCRIPTED_BLOCK_SMB_EVALUATION_EPISODES,
    SCRIPTED_BLOCK_SMB_EVALUATION_MAX_STEPS,
    SCRIPTED_BLOCK_SMB_POLICY_NAME,
    SCRIPTED_BLOCK_SMB_SEED,
    BlockSMBScriptedPolicy,
    evaluate_scripted_block_smb_policy,
    fixed_scenario_action_scripts,
    load_scripted_block_smb_checkpoint,
    save_scripted_block_smb_checkpoint,
)
from .vision import (
    BLOCK_SEMANTIC_CLASSES,
    DEFAULT_BLOCK_VIT_CHECKPOINT,
    FALLBACK_BLOCK_VIT_CHECKPOINT,
    BlockVITLoadResult,
    BlockVITPerceptionThresholds,
    BlockVisionTransformer,
    evaluate_block_vit_perception,
    load_block_vit_checkpoint,
    set_block_vit_trainable,
)

__all__ = [
    "BLOCK_SMB_CHECKPOINT_KIND",
    "BLOCK_SMB_MODEL_NAME",
    "BlockSMBReplayBuffer",
    "BlockSMBTrainingConfig",
    "BlockSMBTrajectory",
    "BlockSMBTransition",
    "SequentialBlockSMBVectorEnv",
    "build_curriculum",
    "evaluate_block_smb",
    "restore_block_smb_checkpoint",
    "save_block_smb_checkpoint",
    "train_and_evaluate_block_smb",
    "train_block_smb_epoch",
    "BLOCK_SEMANTIC_CLASSES",
    "BLOCK_SMB_SPEC",
    "BlockSMBObservationConfig",
    "BlockSMBRewardConfig",
    "BlockSMBSuccessThreshold",
    "BlockSMBScriptedPolicy",
    "BlockSMBStage",
    "BlockVITLoadResult",
    "BlockVITPerceptionThresholds",
    "BlockVisionTransformer",
    "DEFAULT_BLOCK_VIT_CHECKPOINT",
    "FALLBACK_BLOCK_VIT_CHECKPOINT",
    "FIXED_BLOCK_SMB_SUCCESS_THRESHOLDS",
    "MarioScenarioEnv",
    "SCRIPTED_BLOCK_SMB_CHECKPOINT_KIND",
    "SCRIPTED_BLOCK_SMB_EVALUATION_EPISODES",
    "SCRIPTED_BLOCK_SMB_EVALUATION_MAX_STEPS",
    "SCRIPTED_BLOCK_SMB_POLICY_NAME",
    "SCRIPTED_BLOCK_SMB_SEED",
    "SCENARIOS_DIR",
    "evaluate_fixed_success_thresholds",
    "evaluate_block_vit_perception",
    "evaluate_scripted_block_smb_policy",
    "evaluate_success_threshold",
    "fixed_scenario_action_scripts",
    "fixed_scenario_success_threshold",
    "load_scripted_block_smb_checkpoint",
    "load_block_vit_checkpoint",
    "save_scripted_block_smb_checkpoint",
    "set_block_vit_trainable",
    "summarize_fixed_success_metrics",
]
