"""Shared interfaces and model components for all training stages."""

from .actions import (
    SMB_ACTIONS,
    SMBAction,
    block_smb_action,
    coerce_smb_action,
    full_smb_action,
)
from .architectures import (
    ARCHITECTURE_REGISTRY,
    BASELINE_ARCHITECTURE_NAME,
    BASELINE_ARCHITECTURE_SPEC,
    ArchitectureFactory,
    ArchitectureRegistry,
    ArchitectureSpec,
    architecture_names,
    build_architecture,
    get_architecture,
    register_architecture,
)
from .checkpoint import (
    CHECKPOINT_SCHEMA_KEY,
    CHECKPOINT_SCHEMA_VERSION,
    CheckpointPayload,
    build_checkpoint,
    checkpoint_summary,
    checkpoint_summary_path,
    checkpoint_trace_metadata,
    collect_code_revision_metadata,
    collect_runtime_environment_metadata,
    is_versioned_checkpoint,
    load_checkpoint,
    save_checkpoint,
    validate_checkpoint,
    write_checkpoint_summary,
)
from .compatibility import (
    CompatibilityError,
    validate_checkpoint_compatibility,
    validate_model_vision_compatibility,
    validate_stage_spec,
)
from .config import (
    CheckpointConfig,
    EnvironmentConfig,
    EvaluationConfig,
    ExperimentConfig,
    ModelConfig,
    TrainingConfig,
    to_plain_data,
)
from .devices import is_mps_available, is_mps_built, select_device
from .hierarchy import VisionHierarchyProjector
from .interfaces import (
    AgentStep,
    StageBatch,
    StageSpec,
    VisionEncoder,
    VisionOutput,
    VisionSpec,
)
from .models import (
    SUPPORTED_CONTROLLER_SCHEDULES,
    AdaptiveController,
    AgentWorldModelCritic,
    Critic,
    HierarchicalAdaptiveModel,
    PositionalEncoding,
    WorldModel,
    WorldModelState,
)
from .tracking import (
    TRACKING_BACKENDS,
    ExperimentTrackerConfig,
    NullExperimentTracker,
    flatten_numeric_metrics,
    make_experiment_tracker,
)
from .vision import LinearVisionEncoder, PatchVisionTransformer

__all__ = [
    "AdaptiveController",
    "AgentStep",
    "AgentWorldModelCritic",
    "ARCHITECTURE_REGISTRY",
    "ArchitectureFactory",
    "ArchitectureRegistry",
    "ArchitectureSpec",
    "BASELINE_ARCHITECTURE_NAME",
    "BASELINE_ARCHITECTURE_SPEC",
    "CHECKPOINT_SCHEMA_KEY",
    "CHECKPOINT_SCHEMA_VERSION",
    "Critic",
    "CheckpointConfig",
    "CheckpointPayload",
    "CompatibilityError",
    "EnvironmentConfig",
    "EvaluationConfig",
    "ExperimentTrackerConfig",
    "ExperimentConfig",
    "HierarchicalAdaptiveModel",
    "LinearVisionEncoder",
    "ModelConfig",
    "PatchVisionTransformer",
    "PositionalEncoding",
    "SMB_ACTIONS",
    "SMBAction",
    "SUPPORTED_CONTROLLER_SCHEDULES",
    "TRACKING_BACKENDS",
    "StageBatch",
    "StageSpec",
    "TrainingConfig",
    "VisionEncoder",
    "VisionHierarchyProjector",
    "VisionOutput",
    "VisionSpec",
    "WorldModel",
    "WorldModelState",
    "architecture_names",
    "block_smb_action",
    "build_checkpoint",
    "build_architecture",
    "checkpoint_summary",
    "checkpoint_summary_path",
    "checkpoint_trace_metadata",
    "collect_code_revision_metadata",
    "collect_runtime_environment_metadata",
    "coerce_smb_action",
    "flatten_numeric_metrics",
    "full_smb_action",
    "get_architecture",
    "is_versioned_checkpoint",
    "is_mps_available",
    "is_mps_built",
    "load_checkpoint",
    "make_experiment_tracker",
    "NullExperimentTracker",
    "register_architecture",
    "save_checkpoint",
    "select_device",
    "to_plain_data",
    "validate_checkpoint_compatibility",
    "validate_model_vision_compatibility",
    "validate_stage_spec",
    "validate_checkpoint",
    "write_checkpoint_summary",
]
